[package]
name = "starter-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "algo"
path = "src/algo.rs"

[[bin]]
name = "starter-rust"
path = "src/main.rs"

[dependencies]
image = "0.24.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.38"
